API FETCHING

In [5]:
import fetch

In [1]:
parameters_of_the_model = [
    "ALLSKY_SFC_SW_DWN",     # Surface shortwave downwelling (total solar)
    "ALLSKY_SFC_SW_DIFF",    # Diffuse shortwave radiation
    "ALLSKY_SFC_SW_DNI",     # Direct normal irradiance
    "SI_TILTED_AVG",         # Tilted surface irradiance (PV specific)
    "TOA_SW_DWN",            # Top-of-atmosphere solar radiation
    "AIRMASS_HR",            # Air mass (optical depth indicator)
    "T2M",                   # Air temperature at 2 meters
    "RH2M",                  # Relative humidity at 2 meters
    "QV2M",                  # Specific humidity at 2 meters
    "PS",                    # Surface pressure
    "WS2M",                  # Wind speed at 2 meters
    "CLOUD_AMT",             # Total cloud amount
    "ALLSKY_SFC_LW_DWN",     # Downward longwave radiation
    "ALLSKY_SRF_ALB",        # Surface albedo (reflectivity)
    "SG_SZA_HR" 
]

In [ ]:
# for i in parameters_of_the_model:
#     try:
#         fetch.fetch_and_save(i,18.5204,73.8567,"pune")
#     except:
#         print(f"failed to download {i}")

🔍 Fetching ALLSKY_SFC_SW_DWN for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: pune_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: pune_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
failed to download ALLSKY_SFC_SW_DNI
🔍 Fetching SI_TILTED_AVG for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
failed to download SI_TILTED_AVG
🔍 Fetching TOA_SW_DWN for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: pune_TOA_SW_DWN_hourly.csv
🔍 Fetching AIRMASS_HR for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
failed to download AIRMASS_HR
🔍 Fetching T2M for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: pune_T2M_hourly.csv
🔍 Fetching RH2M for pune
https://power.larc.nasa.gov/api/temporal/hourly/point
failed to download RH2M
🔍 Fetching QV2M for pune
https://power.larc.nasa.gov/api/temporal/hourly/point

In [2]:
failed_parameters = ["SG_SZA_HR","T2M","AIRMASS_HR","SI_TILTED_AVG"]

In [ ]:
for i in failed_parameters:
    try:
        fetch.fetch_and_save(i,18.5204,73.8567,"pune")
    except:
        print(f"failed to download {i}")

🔍 Fetching SG_SZA_HR for pune
failed to download SG_SZA_HR
🔍 Fetching T2M for pune
✅ Saved: pune_T2M_hourly.csv
🔍 Fetching AIRMASS_HR for pune
failed to download AIRMASS_HR
🔍 Fetching SI_TILTED_AVG for pune
failed to download SI_TILTED_AVG

In [6]:
import pandas as pd

In [3]:
for i in failed_parameters:
    parameters_of_the_model.remove(i)

In [4]:
parameters_of_the_model.append("T2M")

In [7]:
df = pd.DataFrame()

In [8]:
for i in range(len(parameters_of_the_model)):
    df_temp = pd.read_csv("pune_"+parameters_of_the_model[i]+'_hourly.csv')
    if i!=0:
        df_temp.drop(columns='datetime',axis=1,inplace=True)
    df = pd.concat([df,df_temp],axis=1)

In [9]:
print(df.describe())

       ALLSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DIFF  ALLSKY_SFC_SW_DNI   TOA_SW_DWN  \
count        8784.000000         8784.000000        8784.000000  8784.000000
mean          -99.705452         -186.674572        -140.122668    27.966859
std           579.959770          484.225700         539.056102   722.848464
min          -999.000000         -999.000000        -999.000000  -999.000000
25%          -999.000000         -999.000000        -999.000000  -999.000000
50%             0.000000            0.000000           0.000000     0.000000
75%           239.462500          137.000000         127.255000   563.825000
max          1032.750000          480.330000         895.260000  1328.950000

              RH2M         QV2M           PS         WS2M    CLOUD_AMT  \
count  8784.000000  8784.000000  8784.000000  8784.000000  8784.000000
mean     61.936918     5.174197    84.942418    -5.620997  -227.012757
std      99.981806    91.418355    98.546336    90.325880   451.842382
min    -999.000000  -999.000000  -999.000000  -999.000000  -999.000000
25%      52.042500     8.770000    93.680000     1.310000  -999.000000
50%      78.350000    14.395000    93.930000     2.220000     4.350000
75%      94.492500    17.950000    94.140000     3.430000    48.332500
max     100.000000    21.060000    94.710000     8.850000   100.000000

       ALLSKY_SFC_LW_DWN  ALLSKY_SRF_ALB          T2M
count        8784.000000     8784.000000  8784.000000
mean           32.980763     -623.535628    15.553081
std           603.135355      483.926958    92.394257
min          -999.000000     -999.000000  -999.000000
25%          -999.000000     -999.000000    21.130000
50%           364.600000     -999.000000    23.370000
75%           405.830000        0.100000    26.460000
max           473.400000        0.240000    41.980000

In [11]:
df.drop(columns="ALLSKY_SRF_ALB",inplace=True,axis=1)

In [12]:
df.to_csv("final.csv")

In [ ]:
training_parameters = [ 
        "datetime",
        "ALLSKY_SFC_SW_DIFF",
        "ALLSKY_SFC_SW_DNI",
        "TOA_SW_DWN",
        "RH2M",
        "QV2M",
        "PS",
        "WS2M",
        "CLOUD_AMT",
        "ALLSKY_SFC_LW_DWN",
        "T2M"
    ]

In [ ]:
target_parameter = "ALLSKY_SFC_SW_DWN"

In [ ]:
import numpy as np

In [ ]:
df_test = df.replace(-999.0,0)

In [ ]:
df.drop(columns="ALLSKY_SRF_ALB",axis=1,inplace=True)

In [ ]:
df['ALLSKY_SFC_SW_DWN'] = df['ALLSKY_SFC_SW_DWN'].replace(-999.00,-1)

In [ ]:
df = df.replace(-999.0,-1)

In [ ]:
df.head()

,datetime,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,TOA_SW_DWN,RH2M,QV2M,PS,WS2M,CLOUD_AMT,ALLSKY_SFC_LW_DWN,T2M
0,2024-07-31 00:00:00,0.0,0.0,0.0,0.0,97.44,18.08,93.55,3.71,99.93,415.50,22.70
1,2024-07-31 01:00:00,0.0,0.0,0.0,0.0,97.41,18.05,93.51,3.76,100.00,414.02,22.67
2,2024-07-31 02:00:00,0.0,0.0,0.0,0.0,97.73,17.95,93.48,3.22,99.84,415.48,22.52
3,2024-07-31 03:00:00,0.0,0.0,0.0,0.0,97.69,17.82,93.48,3.05,99.97,416.20,22.41
4,2024-07-31 04:00:00,0.0,0.0,0.0,0.0,97.74,17.76,93.50,3.09,100.00,417.15,22.35

In [ ]:
df.describe()

,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,TOA_SW_DWN,RH2M,QV2M,PS,WS2M,CLOUD_AMT,ALLSKY_SFC_LW_DWN,T2M
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,153.884712,66.915592,113.467495,281.557023,70.117246,13.354525,93.122746,2.559331,26.577407,286.570927,23.733408
std,262.665959,105.965320,209.099745,436.336701,27.105957,4.946523,8.562938,1.598033,37.104199,170.613094,5.833219
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,-1.000000,-1.000000,-1.000000,-1.000000,52.042500,8.770000,93.680000,1.310000,-1.000000,-1.000000,21.130000
50%,0.000000,0.000000,0.000000,0.000000,78.350000,14.395000,93.930000,2.220000,4.350000,364.600000,23.370000
75%,239.462500,137.000000,127.255000,563.825000,94.492500,17.950000,94.140000,3.430000,48.332500,405.830000,26.460000
max,1032.750000,480.330000,895.260000,1328.950000,100.000000,21.060000,94.710000,8.850000,100.000000,473.400000,41.980000

In [ ]:
X ,Y = df[training_parameters],df[target_parameter]

0       2024-07-31 00:00:00
1       2024-07-31 01:00:00
2       2024-07-31 02:00:00
3       2024-07-31 03:00:00
4       2024-07-31 04:00:00
               ...
8779    2025-07-31 19:00:00
8780    2025-07-31 20:00:00
8781    2025-07-31 21:00:00
8782    2025-07-31 22:00:00
8783    2025-07-31 23:00:00
Name: datetime, Length: 8784, dtype: object

In [ ]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['hour'] = df['datetime'].dt.hour
df['month'] = df['datetime'].dt.month
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

In [ ]:
df.head()

,datetime,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,TOA_SW_DWN,RH2M,QV2M,PS,WS2M,CLOUD_AMT,ALLSKY_SFC_LW_DWN,T2M,hour,month,hour_sin,hour_cos,month_sin,month_cos
0,2024-07-31 00:00:00,0.0,0.0,0.0,0.0,97.44,18.08,93.55,3.71,99.93,415.50,22.70,0,7,0.000000,1.000000,-0.5,-0.866025
1,2024-07-31 01:00:00,0.0,0.0,0.0,0.0,97.41,18.05,93.51,3.76,100.00,414.02,22.67,1,7,0.258819,0.965926,-0.5,-0.866025
2,2024-07-31 02:00:00,0.0,0.0,0.0,0.0,97.73,17.95,93.48,3.22,99.84,415.48,22.52,2,7,0.500000,0.866025,-0.5,-0.866025
3,2024-07-31 03:00:00,0.0,0.0,0.0,0.0,97.69,17.82,93.48,3.05,99.97,416.20,22.41,3,7,0.707107,0.707107,-0.5,-0.866025
4,2024-07-31 04:00:00,0.0,0.0,0.0,0.0,97.74,17.76,93.50,3.09,100.00,417.15,22.35,4,7,0.866025,0.500000,-0.5,-0.866025