API FETCHING

In [1]:
import fetch

In [10]:
parameters_of_the_model = [
    "ALLSKY_SFC_SW_DWN",     # Surface shortwave downwelling (total solar)
    "ALLSKY_SFC_SW_DIFF",    # Diffuse shortwave radiation
    "ALLSKY_SFC_SW_DNI",     # Direct normal irradiance
    "TOA_SW_DWN",            # Top-of-atmosphere solar radiation
    "T2M",                   # Air temperature at 2 meters
    "RH2M",                  # Relative humidity at 2 meters
    "QV2M",                  # Specific humidity at 2 meters
    "PS",                    # Surface pressure
    "WS2M",                  # Wind speed at 2 meters
    "CLOUD_AMT",             # Total cloud amount
    "ALLSKY_SFC_LW_DWN",     # Downward longwave radiation
    "ALLSKY_SRF_ALB",        # Surface albedo (reflectivity)
]

In [3]:
capitals_with_coords = [
    ["Amaravati", 16.5417, 80.5170],
    ["Itanagar", 27.0844, 93.6053],
    ["Dispur", 26.1445, 91.7362],
    ["Patna", 25.5941, 85.1376],
    ["Raipur", 21.2514, 81.6296],
    ["Panaji", 15.4909, 73.8278],
    ["Gandhinagar", 23.2156, 72.6369],
    ["Chandigarh", 30.7333, 76.7794],
    ["Shimla", 31.1048, 77.1734],
    ["Ranchi", 23.3441, 85.3096],
    ["Bengaluru", 12.9716, 77.5946],
    ["Thiruvananthapuram", 8.5241, 76.9366],
    ["Bhopal", 23.2599, 77.4126],
    ["Mumbai", 19.0760, 72.8777],
    ["Imphal", 24.8170, 93.9368],
    ["Shillong", 25.5788, 91.8933],
    ["Aizawl", 23.7271, 92.7176],
    ["Kohima", 25.6701, 94.1077],
    ["Bhubaneswar", 20.2961, 85.8245],
    ["Jaipur", 26.9124, 75.7873],
    ["Gangtok", 27.3389, 88.6065],
    ["Chennai", 13.0827, 80.2707],
    ["Hyderabad", 17.3850, 78.4867],
    ["Agartala", 23.8315, 91.2868],
    ["Lucknow", 26.8467, 80.9462],
    ["Dehradun", 30.3165, 78.0322],
    ["Kolkata", 22.5726, 88.3639]
]

In [4]:
for j in capitals_with_coords:
    for i in parameters_of_the_model:
        try:
            fetch.fetch_and_save(i,j[1],j[2],j[0])
        except:
            print(f"failed to download {i}")

🔍 Fetching ALLSKY_SFC_SW_DWN for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_T2M_hourly.csv
🔍 Fetching RH2M for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_RH2M_hourly.csv
🔍 Fetching QV2M for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_QV2M_hourly.csv
🔍 Fetching PS for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_PS_hourly.csv
🔍 Fetching WS2M for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Amaravati
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/amaravati_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_T2M_hourly.csv
🔍 Fetching RH2M for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_RH2M_hourly.csv
🔍 Fetching QV2M for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_QV2M_hourly.csv
🔍 Fetching PS for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_PS_hourly.csv
🔍 Fetching WS2M for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Itanagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/itanagar_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_T2M_hourly.csv
🔍 Fetching RH2M for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_RH2M_hourly.csv
🔍 Fetching QV2M for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_QV2M_hourly.csv
🔍 Fetching PS for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_PS_hourly.csv
🔍 Fetching WS2M for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Dispur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/dispur_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_T2M_hourly.csv
🔍 Fetching RH2M for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_RH2M_hourly.csv
🔍 Fetching QV2M for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_QV2M_hourly.csv
🔍 Fetching PS for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_PS_hourly.csv
🔍 Fetching WS2M for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Patna
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/patna_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_T2M_hourly.csv
🔍 Fetching RH2M for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_RH2M_hourly.csv
🔍 Fetching QV2M for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_QV2M_hourly.csv
🔍 Fetching PS for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_PS_hourly.csv
🔍 Fetching WS2M for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Raipur
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/raipur_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_T2M_hourly.csv
🔍 Fetching RH2M for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_RH2M_hourly.csv
🔍 Fetching QV2M for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_QV2M_hourly.csv
🔍 Fetching PS for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_PS_hourly.csv
🔍 Fetching WS2M for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Panaji
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/panaji_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_T2M_hourly.csv
🔍 Fetching RH2M for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_RH2M_hourly.csv
🔍 Fetching QV2M for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_QV2M_hourly.csv
🔍 Fetching PS for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_PS_hourly.csv
🔍 Fetching WS2M for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Gandhinagar
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/gandhinagar_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_T2M_hourly.csv
🔍 Fetching RH2M for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_RH2M_hourly.csv
🔍 Fetching QV2M for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_QV2M_hourly.csv
🔍 Fetching PS for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
failed to download PS
🔍 Fetching WS2M for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Chandigarh
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/chandigarh_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_T2M_hourly.csv
🔍 Fetching RH2M for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_RH2M_hourly.csv
🔍 Fetching QV2M for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
failed to download QV2M
🔍 Fetching PS for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_PS_hourly.csv
🔍 Fetching WS2M for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Shimla
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/shimla_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_T2M_hourly.csv
🔍 Fetching RH2M for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_RH2M_hourly.csv
🔍 Fetching QV2M for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_QV2M_hourly.csv
🔍 Fetching PS for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_PS_hourly.csv
🔍 Fetching WS2M for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Ranchi
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/ranchi_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_T2M_hourly.csv
🔍 Fetching RH2M for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_RH2M_hourly.csv
🔍 Fetching QV2M for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_QV2M_hourly.csv
🔍 Fetching PS for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_PS_hourly.csv
🔍 Fetching WS2M for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
failed to download WS2M
🔍 Fetching CLOUD_AMT for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Bengaluru
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bengaluru_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_ALLSKY_SFC_SW_DIFF_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DNI for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_ALLSKY_SFC_SW_DNI_hourly.csv
🔍 Fetching TOA_SW_DWN for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_TOA_SW_DWN_hourly.csv
🔍 Fetching T2M for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_T2M_hourly.csv
🔍 Fetching RH2M for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_RH2M_hourly.csv
🔍 Fetching QV2M for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_QV2M_hourly.csv
🔍 Fetching PS for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_PS_hourly.csv
🔍 Fetching WS2M for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_WS2M_hourly.csv
🔍 Fetching CLOUD_AMT for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_CLOUD_AMT_hourly.csv
🔍 Fetching ALLSKY_SFC_LW_DWN for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_ALLSKY_SFC_LW_DWN_hourly.csv
🔍 Fetching ALLSKY_SRF_ALB for Thiruvananthapuram
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/thiruvananthapuram_ALLSKY_SRF_ALB_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DWN for Bhopal
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/bhopal_ALLSKY_SFC_SW_DWN_hourly.csv
🔍 Fetching ALLSKY_SFC_SW_DIFF for Bhopal
https://power.larc.nasa.gov/api/temporal/hourly/point

In [2]:
failed_parameters = ["SG_SZA_HR","T2M","AIRMASS_HR","SI_TILTED_AVG"]

In [26]:
fetch.fetch_and_save("WS2M", 22.5726, 88.3639, "Kolkata")         # ❌ failed: dataset/kolkata_WS2M_hourly.csv not saved (likely Status code 400)

🔍 Fetching WS2M for Kolkata
https://power.larc.nasa.gov/api/temporal/hourly/point
✅ Saved: dataset/kolkata_WS2M_hourly.csv

In [ ]:
for i in failed_parameters:
    try:
        fetch.fetch_and_save(i,18.5204,73.8567,"pune")
    except:
        print(f"failed to download {i}")

🔍 Fetching SG_SZA_HR for pune
failed to download SG_SZA_HR
🔍 Fetching T2M for pune
✅ Saved: pune_T2M_hourly.csv
🔍 Fetching AIRMASS_HR for pune
failed to download AIRMASS_HR
🔍 Fetching SI_TILTED_AVG for pune
failed to download SI_TILTED_AVG

In [6]:
import pandas as pd

In [27]:
# List of capital names (same order used while saving CSVs)
capitals = [
    "Amaravati", "Itanagar", "Dispur", "Patna", "Raipur", "Panaji", "Gandhinagar",
    "Chandigarh", "Shimla", "Ranchi", "Bengaluru", "Thiruvananthapuram", "Bhopal",
    "Mumbai", "Imphal", "Shillong", "Aizawl", "Kohima", "Bhubaneswar", "Jaipur",
    "Gangtok", "Chennai", "Hyderabad", "Agartala", "Lucknow", "Dehradun", "Kolkata"
]



# For each capital city
all_city_data = {}

for city in capitals:
    df_city = None
    for i, param in enumerate(parameters_of_the_model):
        file_path = f"dataset/{city.lower()}_{param}_hourly.csv"
        try:
            df_temp = pd.read_csv(file_path)
        except:
            print(file_path)
            continue;

        # Drop duplicate datetime columns
        if i != 0:
            df_temp.drop(columns='datetime', inplace=True)

        df_city = pd.concat([df_city, df_temp], axis=1) if df_city is not None else df_temp

    all_city_data[city] = df_city

In [30]:
all_city_data.keys()

dict_keys(['Amaravati', 'Itanagar', 'Dispur', 'Patna', 'Raipur', 'Panaji', 'Gandhinagar', 'Chandigarh', 'Shimla', 'Ranchi', 'Bengaluru', 'Thiruvananthapuram', 'Bhopal', 'Mumbai', 'Imphal', 'Shillong', 'Aizawl', 'Kohima', 'Bhubaneswar', 'Jaipur', 'Gangtok', 'Chennai', 'Hyderabad', 'Agartala', 'Lucknow', 'Dehradun', 'Kolkata'])

In [31]:
# Merge all city dataframes into one for model training
merged_df = pd.concat([df for df in all_city_data.values() if df is not None], ignore_index=True)
print(f"Merged dataframe shape: {merged_df.shape}")
merged_df.head()

Merged dataframe shape: (237168, 13)

,datetime,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,TOA_SW_DWN,T2M,RH2M,QV2M,PS,WS2M,CLOUD_AMT,ALLSKY_SFC_LW_DWN,ALLSKY_SRF_ALB
0,2024-08-02 00:00:00,0.0,0.0,0.0,0.0,25.91,93.01,19.62,99.84,2.42,99.90,430.65,-999.0
1,2024-08-02 01:00:00,0.0,0.0,0.0,0.0,25.72,93.74,19.56,99.79,2.42,99.98,427.98,-999.0
2,2024-08-02 02:00:00,0.0,0.0,0.0,0.0,25.54,94.37,19.49,99.75,2.38,100.00,428.50,-999.0
3,2024-08-02 03:00:00,0.0,0.0,0.0,0.0,25.39,94.79,19.40,99.76,2.25,100.00,425.83,-999.0
4,2024-08-02 04:00:00,0.0,0.0,0.0,0.0,25.23,95.24,19.30,99.79,2.05,99.95,424.73,-999.0

In [32]:
merged_df.to_csv("dataset/final.csv")

In [4]:
parameters_of_the_model.append("T2M")

In [7]:
df = pd.DataFrame()

In [8]:
for i in range(len(parameters_of_the_model)):
    df_temp = pd.read_csv("pune_"+parameters_of_the_model[i]+'_hourly.csv')
    if i!=0:
        df_temp.drop(columns='datetime',axis=1,inplace=True)
    df = pd.concat([df,df_temp],axis=1)

In [9]:
print(df.describe())

       ALLSKY_SFC_SW_DWN  ALLSKY_SFC_SW_DIFF  ALLSKY_SFC_SW_DNI   TOA_SW_DWN  \
count        8784.000000         8784.000000        8784.000000  8784.000000
mean          -99.705452         -186.674572        -140.122668    27.966859
std           579.959770          484.225700         539.056102   722.848464
min          -999.000000         -999.000000        -999.000000  -999.000000
25%          -999.000000         -999.000000        -999.000000  -999.000000
50%             0.000000            0.000000           0.000000     0.000000
75%           239.462500          137.000000         127.255000   563.825000
max          1032.750000          480.330000         895.260000  1328.950000

              RH2M         QV2M           PS         WS2M    CLOUD_AMT  \
count  8784.000000  8784.000000  8784.000000  8784.000000  8784.000000
mean     61.936918     5.174197    84.942418    -5.620997  -227.012757
std      99.981806    91.418355    98.546336    90.325880   451.842382
min    -999.000000  -999.000000  -999.000000  -999.000000  -999.000000
25%      52.042500     8.770000    93.680000     1.310000  -999.000000
50%      78.350000    14.395000    93.930000     2.220000     4.350000
75%      94.492500    17.950000    94.140000     3.430000    48.332500
max     100.000000    21.060000    94.710000     8.850000   100.000000

       ALLSKY_SFC_LW_DWN  ALLSKY_SRF_ALB          T2M
count        8784.000000     8784.000000  8784.000000
mean           32.980763     -623.535628    15.553081
std           603.135355      483.926958    92.394257
min          -999.000000     -999.000000  -999.000000
25%          -999.000000     -999.000000    21.130000
50%           364.600000     -999.000000    23.370000
75%           405.830000        0.100000    26.460000
max           473.400000        0.240000    41.980000

In [11]:
df.drop(columns="ALLSKY_SRF_ALB",inplace=True,axis=1)

In [12]:
df.to_csv("final.csv")

In [ ]:
training_parameters = [ 
        "datetime",
        "ALLSKY_SFC_SW_DIFF",
        "ALLSKY_SFC_SW_DNI",
        "TOA_SW_DWN",
        "RH2M",
        "QV2M",
        "PS",
        "WS2M",
        "CLOUD_AMT",
        "ALLSKY_SFC_LW_DWN",
        "T2M"
    ]

In [ ]:
target_parameter = "ALLSKY_SFC_SW_DWN"

In [ ]:
import numpy as np

In [ ]:
df_test = df.replace(-999.0,0)

In [ ]:
df.drop(columns="ALLSKY_SRF_ALB",axis=1,inplace=True)

In [ ]:
df['ALLSKY_SFC_SW_DWN'] = df['ALLSKY_SFC_SW_DWN'].replace(-999.00,-1)

In [ ]:
df = df.replace(-999.0,-1)

In [ ]:
df.head()

,datetime,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,TOA_SW_DWN,RH2M,QV2M,PS,WS2M,CLOUD_AMT,ALLSKY_SFC_LW_DWN,T2M
0,2024-07-31 00:00:00,0.0,0.0,0.0,0.0,97.44,18.08,93.55,3.71,99.93,415.50,22.70
1,2024-07-31 01:00:00,0.0,0.0,0.0,0.0,97.41,18.05,93.51,3.76,100.00,414.02,22.67
2,2024-07-31 02:00:00,0.0,0.0,0.0,0.0,97.73,17.95,93.48,3.22,99.84,415.48,22.52
3,2024-07-31 03:00:00,0.0,0.0,0.0,0.0,97.69,17.82,93.48,3.05,99.97,416.20,22.41
4,2024-07-31 04:00:00,0.0,0.0,0.0,0.0,97.74,17.76,93.50,3.09,100.00,417.15,22.35

In [ ]:
df.describe()

,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,TOA_SW_DWN,RH2M,QV2M,PS,WS2M,CLOUD_AMT,ALLSKY_SFC_LW_DWN,T2M
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,153.884712,66.915592,113.467495,281.557023,70.117246,13.354525,93.122746,2.559331,26.577407,286.570927,23.733408
std,262.665959,105.965320,209.099745,436.336701,27.105957,4.946523,8.562938,1.598033,37.104199,170.613094,5.833219
min,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,-1.000000,-1.000000,-1.000000,-1.000000,52.042500,8.770000,93.680000,1.310000,-1.000000,-1.000000,21.130000
50%,0.000000,0.000000,0.000000,0.000000,78.350000,14.395000,93.930000,2.220000,4.350000,364.600000,23.370000
75%,239.462500,137.000000,127.255000,563.825000,94.492500,17.950000,94.140000,3.430000,48.332500,405.830000,26.460000
max,1032.750000,480.330000,895.260000,1328.950000,100.000000,21.060000,94.710000,8.850000,100.000000,473.400000,41.980000

In [ ]:
X ,Y = df[training_parameters],df[target_parameter]

0       2024-07-31 00:00:00
1       2024-07-31 01:00:00
2       2024-07-31 02:00:00
3       2024-07-31 03:00:00
4       2024-07-31 04:00:00
               ...
8779    2025-07-31 19:00:00
8780    2025-07-31 20:00:00
8781    2025-07-31 21:00:00
8782    2025-07-31 22:00:00
8783    2025-07-31 23:00:00
Name: datetime, Length: 8784, dtype: object

In [ ]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['hour'] = df['datetime'].dt.hour
df['month'] = df['datetime'].dt.month
df['hour_sin'] = np.sin(2 * np.pi * df['hour'] / 24)
df['hour_cos'] = np.cos(2 * np.pi * df['hour'] / 24)
df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

In [ ]:
df.head()

,datetime,ALLSKY_SFC_SW_DWN,ALLSKY_SFC_SW_DIFF,ALLSKY_SFC_SW_DNI,TOA_SW_DWN,RH2M,QV2M,PS,WS2M,CLOUD_AMT,ALLSKY_SFC_LW_DWN,T2M,hour,month,hour_sin,hour_cos,month_sin,month_cos
0,2024-07-31 00:00:00,0.0,0.0,0.0,0.0,97.44,18.08,93.55,3.71,99.93,415.50,22.70,0,7,0.000000,1.000000,-0.5,-0.866025
1,2024-07-31 01:00:00,0.0,0.0,0.0,0.0,97.41,18.05,93.51,3.76,100.00,414.02,22.67,1,7,0.258819,0.965926,-0.5,-0.866025
2,2024-07-31 02:00:00,0.0,0.0,0.0,0.0,97.73,17.95,93.48,3.22,99.84,415.48,22.52,2,7,0.500000,0.866025,-0.5,-0.866025
3,2024-07-31 03:00:00,0.0,0.0,0.0,0.0,97.69,17.82,93.48,3.05,99.97,416.20,22.41,3,7,0.707107,0.707107,-0.5,-0.866025
4,2024-07-31 04:00:00,0.0,0.0,0.0,0.0,97.74,17.76,93.50,3.09,100.00,417.15,22.35,4,7,0.866025,0.500000,-0.5,-0.866025