In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_weather = pd.read_csv('./dataset/unisolar/Weather_Data_reordered_all.csv')

In [32]:
df = df_weather.dropna().reset_index()

In [9]:
df_weather.size

2974152

In [5]:
df_solar = pd.read_csv('./dataset/unisolar/Solar_Energy_Generation.csv')

In [8]:
df_solar.size

10927784

In [28]:
df_solar.dropna().reset_index()

           index  CampusKey  SiteKey            Timestamp  SolarGeneration
0             24          2        1  2020-01-01 06:15:00         0.135000
1             25          2        1  2020-01-01 06:30:00         0.465000
2             26          2        1  2020-01-01 06:45:00         1.039000
3             27          2        1  2020-01-01 07:00:00         1.673000
4             28          2        1  2020-01-01 07:15:00         2.560000
...          ...        ...      ...                  ...              ...
1195640  2731915          5       42  2022-04-23 16:15:00         1.453125
1195641  2731916          5       42  2022-04-23 16:30:00         1.062500
1195642  2731917          5       42  2022-04-23 16:45:00         0.703125
1195643  2731918          5       42  2022-04-23 17:00:00         0.437500
1195644  2731919          5       42  2022-04-23 17:15:00         0.203125

[1195645 rows x 5 columns]

In [30]:
df['Timestamp']==df_solar['Timestamp']

ValueError: Can only compare identically-labeled Series objects

In [ ]:
df['target'] = df_solar[]

,index,CampusKey,Timestamp,ApparentTemperature,AirTemperature,DewPointTemperature,RelativeHumidity,WindSpeed,WindDirection
0,0,1,2020-01-01 00:00:00,13.666667,13.880000,8.960000,72.400000,0.000000,188.133333
1,1,1,2020-01-01 00:15:00,13.206667,13.666667,9.040000,73.466667,1.200000,203.866667
2,2,1,2020-01-01 00:30:00,12.840000,13.553333,9.053333,74.000000,2.520000,222.800000
3,3,1,2020-01-01 00:45:00,12.113333,13.506667,9.100000,74.466667,5.986667,231.133333
4,4,1,2020-01-01 01:00:00,11.946667,13.260000,9.266667,76.533333,5.946667,247.866667